#!/usr/bin/env python3
"""Preprocessing script for data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S06.dta
Output: data/processed/modules/nccs_2022_s06_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S06.dta"
dst = ROOT / "data/processed/modules/nccs_2022_s06_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu": "PSU ID",
    "hhld": "Household ID",
    "f01": "Heard about climate change",
    "f06": "Did you receive Pre-Warning information",
    "f07": "Main source of pre-warning information",
    "f08": "Preparatory work done to protect from disaster",
    "f09a": "Type of preparatory work done to protect-1",
    "f09b": "Type of preparatory work done to protect-2",
    "f09c": "Type of preparatory work done to protect-3",
    "f09d": "Type of preparatory work done to protect-4",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Heard about climate change
df["Heard about climate change"] = df["Heard about climate change"].astype("category")
# Did you receive Pre-Warning information
df["Did you receive Pre-Warning information"] = df["Did you receive Pre-Warning information"].astype("category")
# Main source of pre-warning information
df["Main source of pre-warning information"] = df["Main source of pre-warning information"].astype("category")
# Preparatory work done to protect from disaster
df["Preparatory work done to protect from disaster"] = df["Preparatory work done to protect from disaster"].astype("category")
# Type of preparatory work done to protect-1
df["Type of preparatory work done to protect-1"] = df["Type of preparatory work done to protect-1"].astype("category")
# Type of preparatory work done to protect-2
df["Type of preparatory work done to protect-2"] = df["Type of preparatory work done to protect-2"].astype("category")
# Type of preparatory work done to protect-3
df["Type of preparatory work done to protect-3"] = df["Type of preparatory work done to protect-3"].astype("category")
# Type of preparatory work done to protect-4
df["Type of preparatory work done to protect-4"] = df["Type of preparatory work done to protect-4"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
