#!/usr/bin/env python3
"""Preprocessing script for data/raw/Nepal-Vulnerability/NPL_2016-2018_HRVS_v01_M_STATA12/NPL_2016-2018_HRVS_v01_M_STATA12/Wave 3 - Household/Section_0.dta
Output: data/processed/modules/hrvs_wave_3_section_0_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/Nepal-Vulnerability/NPL_2016-2018_HRVS_v01_M_STATA12/NPL_2016-2018_HRVS_v01_M_STATA12/Wave 3 - Household/Section_0.dta"
dst = ROOT / "data/processed/modules/hrvs_wave_3_section_0_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "hhid": "Household ID",
    "psu": "PSU ID",
    "district": "District",
    "vdc": "VDC",
    "wt_hh": "Survey Weight",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# District
df["District"] = df["District"].astype("category")
# VDC
df["VDC"] = df["VDC"].str.strip()

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
