#!/usr/bin/env python3
"""Preprocessing script for data/raw/NLSS/NLSS IV 2022_23/data/stata format/S03.dta
Output: data/processed/modules/nlss_iv_s03_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NLSS/NLSS IV 2022_23/data/stata format/S03.dta"
dst = ROOT / "data/processed/modules/nlss_iv_s03_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu_number": "PSU ID",
    "dist_name": "District",
    "hh_number": "Household ID",
    "s03_code": "FACILITY CODE",
    "s03_desc": "FACILITY DESCRIPTION",
    "q03_01": "How do you OR would you normally travel to the closest .. FACILITY",
    "q03_02_a": "How long does it take to get from your house to the closest .. FACILITY",
    "q03_02_b": "HOURS",
    "q03_02_c": "MINUTES",
    "q03_03": "How far is the closest FACILITY to this household",
    "q03_04": "Have the members of this household used .. FACILITY .. during the past 12",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# District
df["District"] = df["District"].str.strip()
# FACILITY DESCRIPTION
df["FACILITY DESCRIPTION"] = df["FACILITY DESCRIPTION"].str.strip()
# How do you OR would you normally travel to the closest .. FACILITY
df["How do you OR would you normally travel to the closest .. FACILITY"] = df["How do you OR would you normally travel to the closest .. FACILITY"].astype("category")
# Have the members of this household used .. FACILITY .. during the past 12
df["Have the members of this household used .. FACILITY .. during the past 12"] = df["Have the members of this household used .. FACILITY .. during the past 12"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
