#!/usr/bin/env python3
"""Preprocessing script for data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S06_3.dta
Output: data/processed/modules/nccs_2022_s06_3_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S06_3.dta"
dst = ROOT / "data/processed/modules/nccs_2022_s06_3_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu": "PSU ID",
    "hhld": "Household ID",
    "f15sn": "F.15 S.No",
    "f16desc": "F.16 Type of disaster incidence due to climate change",
    "f17": "F.17 Effect household from disaster incidence during 25 yrs",
    "f18": "F.18 How to effect family from disaster incidence",
    "f19a": "F.19 Cause of disaster incidence - 1",
    "f19b": "F.19 Cause of disaster incidence - 2",
    "f19c": "F.19 Cause of disaster incidence - 3",
    "f20a": "F.20 Efforts made to prevent/minimize disaster events",
    "f20b": "F.20 Efforts made to prevent/minimize disaster events-2",
    "f20c": "F.20 Efforts made to prevent/minimize disaster events-3",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# F.15 S.No
df["F.15 S.No"] = df["F.15 S.No"].astype("category")
# F.16 Type of disaster incidence due to climate change
df["F.16 Type of disaster incidence due to climate change"] = df["F.16 Type of disaster incidence due to climate change"].str.strip()
# F.17 Effect household from disaster incidence during 25 yrs
df["F.17 Effect household from disaster incidence during 25 yrs"] = df["F.17 Effect household from disaster incidence during 25 yrs"].astype("category")
# F.18 How to effect family from disaster incidence
df["F.18 How to effect family from disaster incidence"] = df["F.18 How to effect family from disaster incidence"].astype("category")
# F.19 Cause of disaster incidence - 1
df["F.19 Cause of disaster incidence - 1"] = df["F.19 Cause of disaster incidence - 1"].astype("category")
# F.19 Cause of disaster incidence - 2
df["F.19 Cause of disaster incidence - 2"] = df["F.19 Cause of disaster incidence - 2"].astype("category")
# F.19 Cause of disaster incidence - 3
df["F.19 Cause of disaster incidence - 3"] = df["F.19 Cause of disaster incidence - 3"].astype("category")
# F.20 Efforts made to prevent/minimize disaster events
df["F.20 Efforts made to prevent/minimize disaster events"] = df["F.20 Efforts made to prevent/minimize disaster events"].astype("category")
# F.20 Efforts made to prevent/minimize disaster events-2
df["F.20 Efforts made to prevent/minimize disaster events-2"] = df["F.20 Efforts made to prevent/minimize disaster events-2"].astype("category")
# F.20 Efforts made to prevent/minimize disaster events-3
df["F.20 Efforts made to prevent/minimize disaster events-3"] = df["F.20 Efforts made to prevent/minimize disaster events-3"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
