#!/usr/bin/env python3
"""Preprocessing script for data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S07_1.dta
Output: data/processed/modules/nccs_2022_s07_1_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S07_1.dta"
dst = ROOT / "data/processed/modules/nccs_2022_s07_1_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu": "PSU ID",
    "hhld": "Household ID",
    "g01sn": "G.01 S.No",
    "g02desc": "G.02 Type of disaster incidence",
    "g03yr": "G.03 Years of facing disaster incidence",
    "g04": "G.04 Family affect from disaster incidence",
    "g05": "G.05 Number of days missed to work",
    "g06": "G.06 Family faced food scarcity",
    "g07": "G.07 Have family member disable",
    "g08": "G.08 Have death of family member",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# G.01 S.No
df["G.01 S.No"] = df["G.01 S.No"].astype("category")
# G.02 Type of disaster incidence
df["G.02 Type of disaster incidence"] = df["G.02 Type of disaster incidence"].str.strip()
# G.03 Years of facing disaster incidence
df["G.03 Years of facing disaster incidence"] = df["G.03 Years of facing disaster incidence"].astype("string")
# G.04 Family affect from disaster incidence
df["G.04 Family affect from disaster incidence"] = df["G.04 Family affect from disaster incidence"].astype("category")
# G.06 Family faced food scarcity
df["G.06 Family faced food scarcity"] = df["G.06 Family faced food scarcity"].astype("category")
# G.07 Have family member disable
df["G.07 Have family member disable"] = df["G.07 Have family member disable"].astype("category")
# G.08 Have death of family member
df["G.08 Have death of family member"] = df["G.08 Have death of family member"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
