#!/usr/bin/env python3
"""Preprocessing script for data/raw/NLSS/NLSS IV 2022_23/data/stata format/poverty.dta
Output: data/processed/modules/nlss_iv_poverty_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NLSS/NLSS IV 2022_23/data/stata format/poverty.dta"
dst = ROOT / "data/processed/modules/nlss_iv_poverty_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu_number": "PSU ID",
    "hh_number": "Household ID",
    "prov": "Province Code",
    "domain": "Analytical Domain",
    "hhsize": "Household size",
    "hhs_wt": "Household Survey Weight",
    "ind_wt": "Individual Survey Weight",
    "ad_4": "Urban/rural/ktm_urban",
    "paasche": "Paasche index -- food items",
    "pcep_food": "Per Capita Food Expenditure",
    "pcep_nonfood": "Per Capita Nonfood Expenditure",
    "pcep": "Per Capita Expenditure",
    "pline": "National Real Poverty Line (NPR/person/year)",
    "fpline": "National Real Food Poverty Line (NPR/person/year)",
    "nfpline": "National Real Non-food Poverty Line (NPR/person/year)",
    "poor": "Poverty Status",
    "quintile_pcep": "Expenditure quintile",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Province Code
df["Province Code"] = df["Province Code"].astype("category")
# Analytical Domain
df["Analytical Domain"] = df["Analytical Domain"].astype("category")
# Urban/rural/ktm_urban
df["Urban/rural/ktm_urban"] = df["Urban/rural/ktm_urban"].astype("category")
# Expenditure quintile
df["Expenditure quintile"] = df["Expenditure quintile"].astype("string")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
