#!/usr/bin/env python3
"""Preprocessing script for data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S07_2.dta
Output: data/processed/modules/nccs_2022_s07_2_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S07_2.dta"
dst = ROOT / "data/processed/modules/nccs_2022_s07_2_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu": "PSU ID",
    "hhld": "Household ID",
    "g15sn": "G.15 S.No",
    "g16desc": "G.16 Types of disaster incidence",
    "g17yn": "G.17 Household lost from disaster incidence",
    "g18": "G.18 Loss in residential house/shelter etc. (Rs.)",
    "g19": "G.19 Loss in cereal crops (Rs.)",
    "g20": "G.20 Loss in vegetable crops (Rs.)",
    "g21": "G.21 Loss in fruit crops (Rs.)",
    "g22": "Q.22 Loss in other crops (Rs.)",
    "g23": "G.23 Loss in livestock/poultry (Rs.)",
    "g24": "G.24 Loss in garden/nursary land (Rs.)",
    "g25": "G.25 Loss in productive land (Rs.)",
    "g26": "G.26 Loss in other non-agri. business (Rs.)",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# G.15 S.No
df["G.15 S.No"] = df["G.15 S.No"].astype("category")
# G.16 Types of disaster incidence
df["G.16 Types of disaster incidence"] = df["G.16 Types of disaster incidence"].str.strip()
# G.17 Household lost from disaster incidence
df["G.17 Household lost from disaster incidence"] = df["G.17 Household lost from disaster incidence"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
