#!/usr/bin/env python3
"""Preprocessing script for data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S04.dta
Output: data/processed/modules/nccs_2022_s04_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S04.dta"
dst = ROOT / "data/processed/modules/nccs_2022_s04_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu": "PSU ID",
    "hhld": "Household ID",
    "d01": "Have membership in co-operative / saving groups",
    "d02": "Have regular saving in cooperatives / saving groups",
    "d03": "Regular saving in financial institute/Bank",
    "d04": "Loan taken from Money lender/saving group/co-operatives",
    "d07": "Have involvement in community organisation",
    "d09": "Affiliation in Tole Development committee",
    "d10": "Receive any service from agri. service center",
    "d11": "Distance to ward office (km)",
    "d12": "Distance to motorable road (km)",
    "d13": "Distance to nearest health institution (km)",
    "d14": "Distance to nearest basic school (km)",
    "d15": "Distance to nearest local market (km)",
    "d16": "Distance to nearest Agr/livestock service center (km)",
    "d17": "Modern Equip./machine used in agriculture",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Have membership in co-operative / saving groups
df["Have membership in co-operative / saving groups"] = df["Have membership in co-operative / saving groups"].astype("category")
# Have regular saving in cooperatives / saving groups
df["Have regular saving in cooperatives / saving groups"] = df["Have regular saving in cooperatives / saving groups"].astype("category")
# Regular saving in financial institute/Bank
df["Regular saving in financial institute/Bank"] = df["Regular saving in financial institute/Bank"].astype("category")
# Loan taken from Money lender/saving group/co-operatives
df["Loan taken from Money lender/saving group/co-operatives"] = df["Loan taken from Money lender/saving group/co-operatives"].astype("category")
# Have involvement in community organisation
df["Have involvement in community organisation"] = df["Have involvement in community organisation"].astype("category")
# Affiliation in Tole Development committee
df["Affiliation in Tole Development committee"] = df["Affiliation in Tole Development committee"].astype("category")
# Receive any service from agri. service center
df["Receive any service from agri. service center"] = df["Receive any service from agri. service center"].astype("category")
# Modern Equip./machine used in agriculture
df["Modern Equip./machine used in agriculture"] = df["Modern Equip./machine used in agriculture"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
