#!/usr/bin/env python3
"""Preprocessing script for data/raw/NLSS/NLSS IV 2022_23/data/stata format/S17.dta
Output: data/processed/modules/nlss_iv_s17_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NLSS/NLSS IV 2022_23/data/stata format/S17.dta"
dst = ROOT / "data/processed/modules/nlss_iv_s17_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu_number": "PSU ID",
    "hh_number": "Household ID",
    "q17_01": "Residential facility",
    "q17_02": "Clothing",
    "q17_03": "Health care",
    "q17_04": "Childrens schooling",
    "q17_05": "Total income over the past one month",
    "q17_06_a": "Health facility",
    "q17_06_b": "Health facility (q17_06_b)",
    "q17_07_a": "Education facilities",
    "q17_07_b": "Education facilities (q17_07_b)",
    "q17_08_a": "Drinking water facility",
    "q17_08_b": "Drinking water facility (q17_08_b)",
    "q17_09_a": "Electricity facility",
    "q17_09_b": "Electricity facility (q17_09_b)",
    "q17_10_a": "Road facility",
    "q17_11_a": "Postal facility",
    "q17_11_b": "Postal facility (q17_11_b)",
    "q17_12_a": "Telephone facility",
    "q17_12_b": "Telephone facility (q17_12_b)",
    "q17_13_a": "Internet facility",
    "q17_13_b": "Internet facility (q17_13_b)",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Residential facility
df["Residential facility"] = df["Residential facility"].astype("category")
# Clothing
df["Clothing"] = df["Clothing"].astype("category")
# Health care
df["Health care"] = df["Health care"].astype("category")
# Childrens schooling
df["Childrens schooling"] = df["Childrens schooling"].astype("category")
# Total income over the past one month
df["Total income over the past one month"] = df["Total income over the past one month"].astype("category")
# Health facility
df["Health facility"] = df["Health facility"].astype("category")
# Health facility (q17_06_b)
df["Health facility (q17_06_b)"] = df["Health facility (q17_06_b)"].astype("category")
# Education facilities
df["Education facilities"] = df["Education facilities"].astype("category")
# Education facilities (q17_07_b)
df["Education facilities (q17_07_b)"] = df["Education facilities (q17_07_b)"].astype("category")
# Drinking water facility
df["Drinking water facility"] = df["Drinking water facility"].astype("category")
# Drinking water facility (q17_08_b)
df["Drinking water facility (q17_08_b)"] = df["Drinking water facility (q17_08_b)"].astype("category")
# Electricity facility
df["Electricity facility"] = df["Electricity facility"].astype("category")
# Electricity facility (q17_09_b)
df["Electricity facility (q17_09_b)"] = df["Electricity facility (q17_09_b)"].astype("category")
# Road facility
df["Road facility"] = df["Road facility"].astype("category")
# Postal facility
df["Postal facility"] = df["Postal facility"].astype("category")
# Postal facility (q17_11_b)
df["Postal facility (q17_11_b)"] = df["Postal facility (q17_11_b)"].astype("category")
# Telephone facility
df["Telephone facility"] = df["Telephone facility"].astype("category")
# Telephone facility (q17_12_b)
df["Telephone facility (q17_12_b)"] = df["Telephone facility (q17_12_b)"].astype("category")
# Internet facility
df["Internet facility"] = df["Internet facility"].astype("category")
# Internet facility (q17_13_b)
df["Internet facility (q17_13_b)"] = df["Internet facility (q17_13_b)"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
