#!/usr/bin/env python3
"""Preprocessing script for data/raw/Nepal-Vulnerability/NPL_2016-2018_HRVS_v01_M_STATA12/NPL_2016-2018_HRVS_v01_M_STATA12/Wave 1 - Household/Section_15a.dta
Output: data/processed/modules/hrvs_wave_1_section_15a_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/Nepal-Vulnerability/NPL_2016-2018_HRVS_v01_M_STATA12/NPL_2016-2018_HRVS_v01_M_STATA12/Wave 1 - Household/Section_15a.dta"
dst = ROOT / "data/processed/modules/hrvs_wave_1_section_15a_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "hhid": "Household ID",
    "psu": "PSU ID",
    "district": "District",
    "vdc": "VDC",
    "shockid": "Shock Type",
    "s15q02": "Decrease or loss of income or assets",
    "s15q03": "The monetary value of the loss (in Rupees)",
    "s15q04": "Number of months ago when this shock took place",
    "s15q05a": "Spend savings, borrow money, sell or pawn properties",
    "s15q07a": "Reduce consumption or expenditure on foods",
    "s15q08a": "Reduce consumption or expenditures on non-food items",
    "s15q09a": "Education of children affected by the shock",
    "s15q10a": "Received assistance or help from others",
    "s15q10b_1": "Source of assistance Relatives",
    "s15q10b_2": "Source of assistance Friends/neighbors",
    "s15q10b_3": "Source of assistance Government",
    "s15q10b_4": "Source of assistance NGO/Church",
    "s15q10b_5": "Source of assistance Other",
    "s15q10c_1": "Type of assistance Cash",
    "s15q10c_2": "Type of assistance In Kind (Food)",
    "s15q10c_3": "Type of assistance In Kind (Non Food)",
    "s15q10e": "time taken to receive assistance",
    "s15q11a": "Look for work, got employed or worked more",
    "s15q12a": "Changes in your living arrangements or the number of household members",
    "s15q13a": "First of the two main strategies adopted",
    "s15q13b": "Second of the two main strategies adopted",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# District
df["District"] = df["District"].astype("category")
# VDC
df["VDC"] = df["VDC"].str.strip()
# Shock Type
df["Shock Type"] = df["Shock Type"].astype("category")
# Decrease or loss of income or assets
df["Decrease or loss of income or assets"] = df["Decrease or loss of income or assets"].astype("category")
# Spend savings, borrow money, sell or pawn properties
df["Spend savings, borrow money, sell or pawn properties"] = df["Spend savings, borrow money, sell or pawn properties"].astype("category")
# Reduce consumption or expenditure on foods
df["Reduce consumption or expenditure on foods"] = df["Reduce consumption or expenditure on foods"].astype("category")
# Reduce consumption or expenditures on non-food items
df["Reduce consumption or expenditures on non-food items"] = df["Reduce consumption or expenditures on non-food items"].astype("category")
# Education of children affected by the shock
df["Education of children affected by the shock"] = df["Education of children affected by the shock"].astype("category")
# Received assistance or help from others
df["Received assistance or help from others"] = df["Received assistance or help from others"].astype("category")
# Source of assistance Relatives
df["Source of assistance Relatives"] = df["Source of assistance Relatives"].astype("category")
# Source of assistance Friends/neighbors
df["Source of assistance Friends/neighbors"] = df["Source of assistance Friends/neighbors"].astype("category")
# Source of assistance Government
df["Source of assistance Government"] = df["Source of assistance Government"].astype("category")
# Source of assistance NGO/Church
df["Source of assistance NGO/Church"] = df["Source of assistance NGO/Church"].astype("category")
# Source of assistance Other
df["Source of assistance Other"] = df["Source of assistance Other"].astype("category")
# Type of assistance Cash
df["Type of assistance Cash"] = df["Type of assistance Cash"].astype("category")
# Type of assistance In Kind (Food)
df["Type of assistance In Kind (Food)"] = df["Type of assistance In Kind (Food)"].astype("category")
# Type of assistance In Kind (Non Food)
df["Type of assistance In Kind (Non Food)"] = df["Type of assistance In Kind (Non Food)"].astype("category")
# time taken to receive assistance
df["time taken to receive assistance"] = df["time taken to receive assistance"].str.strip()
# Look for work, got employed or worked more
df["Look for work, got employed or worked more"] = df["Look for work, got employed or worked more"].astype("category")
# Changes in your living arrangements or the number of household members
df["Changes in your living arrangements or the number of household members"] = df["Changes in your living arrangements or the number of household members"].astype("category")
# First of the two main strategies adopted
df["First of the two main strategies adopted"] = df["First of the two main strategies adopted"].astype("category")
# Second of the two main strategies adopted
df["Second of the two main strategies adopted"] = df["Second of the two main strategies adopted"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
