#!/usr/bin/env python3
"""Preprocessing script for data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/Weight.dta
Output: data/processed/modules/nccs_2022_weight_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/Weight.dta"
dst = ROOT / "data/processed/modules/nccs_2022_weight_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "PSU": "PSU ID",
    "HHLD": "Household ID",
    "AltGrp": "Altitude Group",
    "RiskRating": "Risk Rating",
    "Prov": "Province Code",
    "ProvName": "Province",
    "Stratrum": "Stratum ID",
    "StratrumName": "Stratum",
    "UrbRur": "Urban Rural Classification",
    "EcoBelt": "Ecological Belt",
    "Wght": "Survey Weight",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Altitude Group
df["Altitude Group"] = df["Altitude Group"].astype("category")
# Risk Rating
df["Risk Rating"] = df["Risk Rating"].astype("category")
# Province Code
df["Province Code"] = df["Province Code"].astype("category")
# Province
df["Province"] = df["Province"].str.strip()
# Stratum ID
df["Stratum ID"] = df["Stratum ID"].astype("category")
# Stratum
df["Stratum"] = df["Stratum"].str.strip()
# Urban Rural Classification
df["Urban Rural Classification"] = df["Urban Rural Classification"].astype("category")
# Ecological Belt
df["Ecological Belt"] = df["Ecological Belt"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
