#!/usr/bin/env python3
"""Preprocessing script for data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S01.dta
Output: data/processed/modules/nccs_2022_s01_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S01.dta"
dst = ROOT / "data/processed/modules/nccs_2022_s01_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu": "PSU ID",
    "hhld": "Household ID",
    "respsex": "Sex of respondent",
    "respage": "Age of respondent",
    "a13": "Caste/ethnicity of respondent",
    "a14": "Highest level of edu. of respondent",
    "a15": "Years of living this community",
    "b01": "No. of member usually stay",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# Sex of respondent
df["Sex of respondent"] = df["Sex of respondent"].astype("category")
# Caste/ethnicity of respondent
df["Caste/ethnicity of respondent"] = df["Caste/ethnicity of respondent"].astype("category")
# Highest level of edu. of respondent
df["Highest level of edu. of respondent"] = df["Highest level of edu. of respondent"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
