#!/usr/bin/env python3
"""Preprocessing script for data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S11.dta
Output: data/processed/modules/nccs_2022_s11_preprocessed.parquet

Generated by data-preprocessing skill.
"""
from __future__ import annotations

import pandas as pd
from pathlib import Path
import pyreadstat

ROOT = Path(__file__).resolve().parents[2]  # project root

src = ROOT / "data/raw/NICCS/Climate-2022/Data 2022/NCCS 2022/Data/S11.dta"
dst = ROOT / "data/processed/modules/nccs_2022_s11_preprocessed.parquet"

# --- Load ---
df, _ = pyreadstat.read_dta(str(src), apply_value_formats=True)

# --- Select and rename columns ---
rename_map = {
    "psu": "PSU ID",
    "hhld": "Household ID",
    "k01": "K.01 Taking any related agri. adaptation training",
    "k16": "K.16 Insurance made for livestock",
    "k19": "K.19 Insurance made for agri. crops",
    "k31": "K.31 Work on water and land conservation",
    "k32": "Any agri. services received from the local office",
    "k36": "K.36 Work to minimize climatic induced disaster",
    "k38": "K.38 Behaviour change in food consumption",
    "k39": "K.39 Increase non-agri. business locally",
    "k40": "K.40 Shifted in non-agri. employment",
    "k41": "K.41 Having temporary out-migration",
    "k42": "K.42 Participate in flood/landslide risk reduction activities",
    "k43": "K.43 Participate in improvement of road infra",
    "k44": "K.44 Participate in natural resource mgmt",
    "k45": "K.45 Participate in climate induced disaster risk reduction capacity improvement",
}
df = df[list(rename_map.keys())].rename(columns=rename_map)

# --- Variable-level preprocessing ---
# K.01 Taking any related agri. adaptation training
df["K.01 Taking any related agri. adaptation training"] = df["K.01 Taking any related agri. adaptation training"].astype("category")
# K.16 Insurance made for livestock
df["K.16 Insurance made for livestock"] = df["K.16 Insurance made for livestock"].astype("category")
# K.19 Insurance made for agri. crops
df["K.19 Insurance made for agri. crops"] = df["K.19 Insurance made for agri. crops"].astype("category")
# K.31 Work on water and land conservation
df["K.31 Work on water and land conservation"] = df["K.31 Work on water and land conservation"].astype("category")
# Any agri. services received from the local office
df["Any agri. services received from the local office"] = df["Any agri. services received from the local office"].astype("category")
# K.36 Work to minimize climatic induced disaster
df["K.36 Work to minimize climatic induced disaster"] = df["K.36 Work to minimize climatic induced disaster"].astype("category")
# K.38 Behaviour change in food consumption
df["K.38 Behaviour change in food consumption"] = df["K.38 Behaviour change in food consumption"].astype("category")
# K.39 Increase non-agri. business locally
df["K.39 Increase non-agri. business locally"] = df["K.39 Increase non-agri. business locally"].astype("category")
# K.40 Shifted in non-agri. employment
df["K.40 Shifted in non-agri. employment"] = df["K.40 Shifted in non-agri. employment"].astype("category")
# K.41 Having temporary out-migration
df["K.41 Having temporary out-migration"] = df["K.41 Having temporary out-migration"].astype("category")
# K.42 Participate in flood/landslide risk reduction activities
df["K.42 Participate in flood/landslide risk reduction activities"] = df["K.42 Participate in flood/landslide risk reduction activities"].astype("category")
# K.43 Participate in improvement of road infra
df["K.43 Participate in improvement of road infra"] = df["K.43 Participate in improvement of road infra"].astype("category")
# K.44 Participate in natural resource mgmt
df["K.44 Participate in natural resource mgmt"] = df["K.44 Participate in natural resource mgmt"].astype("category")
# K.45 Participate in climate induced disaster risk reduction capacity improvement
df["K.45 Participate in climate induced disaster risk reduction capacity improvement"] = df["K.45 Participate in climate induced disaster risk reduction capacity improvement"].astype("category")

# --- Save ---
dst.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(dst, index=False, engine="pyarrow")
print(f"Saved {len(df):,} rows × {len(df.columns)} cols → {dst.relative_to(ROOT)}")
